version: 2

build:
    os: ubuntu-22.04
    tools:
        python: "3.11"
    commands:
        - cd gbvm && make virex && cd ..
        - pip install -r Documentation/requirements.txt
        - mkdocs build -f Documentation/mkdocs.yml
        - mkdir -p $READTHEDOCS_OUTPUT/html/
        - mv html/* $READTHEDOCS_OUTPUT/html
